name: Publish Documentaion
on:
  push:
    branches:
    - master
jobs:
  update_documentation:
    runs-on: ubuntu-latest
    name: Update Mixture documentation with DocFX
    steps:
      - uses: actions/checkout@v2

      - name: Copy documentation package files to docfx folder
        run: cp Packages/com.alelievr.mixture/Documentation~/ docs/docfx/manual/
        shell: bash

    # Generate documentation website with docfx
      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: docs/docfx/docfx.json
    
      - name: Publish Documentation
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          BRANCH: hg-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch

    # Publish generated site using GitHub Pages
    # - uses: maxheld83/ghpages@master
    #   name: Publish Documentation on GitHub Pages
    #   env:
    #    BUILD_DIR: docs/docfx
    #    GH_PAT: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
